config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => 'weeks#index'
  resources :users do
    resources :weeks
  end
  resources :weeks do
    resources :physical_tasks
    resources :mental_tasks
    resources :ongoing_tasks
    resources :one_and_dones
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mental_task.rb
class MentalTask < ActiveRecord::Base
  belongs_to :week

  validates :description, :presence => true
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_sms
  before_save :define_from
  belongs_to :week

  private

  def define_from
    self.from = "9717035923"
  end

  def send_sms

    begin
      # JSON.parse(to).each do |recipient|
        response = RestClient::Request.new(
        :method => :post,
        :url => 'https://api.twilio.com/2010-04-01/Accounts/AC4cd1074a87b255c311152ea873ddd453/Messages.json',
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :From => from,
                      :To => to }
        ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      throw(:abort)
    end
  end
end

app/models/one_and_done.rb
class OneAndDone < ActiveRecord::Base
  belongs_to :week

  validates :description, :presence => true
end

app/models/ongoing_task.rb
class OngoingTask < ActiveRecord::Base
  belongs_to :week

  validates :description, :presence => true
end

app/models/physical_task.rb
class PhysicalTask < ActiveRecord::Base
  belongs_to :week

  validates :description, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :weeks
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :user
  has_many :physical_tasks
  has_many :mental_tasks
  has_many :ongoing_tasks
  has_many :one_and_dones
  has_many :messages
  validates :date, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @week = Week.find(params[:week_id])
    @message = @week.messages.new
  end

  def create
    @week = Week.find(params[:week_id])
    @message = @week.messages.new(message_params)
    # @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Your message was sent!"
      redirect_to weeks_path
    else
      render 'new'
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  private

    def message_params
      params.require(:message).permit(:body, :to)
    end
  end

app/controllers/physical_tasks_controller.rb
class PhysicalTasksController < ApplicationController
  def new
    @week = Week.find(params[:week_id])
    @physical_task = @week.physical_tasks.new
  end

  def create
    @week = Week.find(params[:week_id])
    @physical_task = @week.physical_tasks.new(physical_task_params)
    if @physical_task.save
      respond_to do |format|
        format.html { redirect_to week_path(@physical_task.week) }
        format.js
      end
    else
      render :new
    end
  end

  def edit
    @week= Week.find(params[:week_id])
    @physical_task = PhysicalTask.find(params[:id])
  end

  def update
    @week= Week.find(params[:week_id])
    @physical_task = PhysicalTask.find(params[:id])
    if @physical_task.update(physical_task_params)
      flash[:notice] = "Task successfully updated!"
      respond_to do |format|
        format.html { redirect_to week_path(@physical_task.week) }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @physical_task = PhysicalTask.find(params[:id])
    @physical_task.destroy
    flash[:notice] = "Task successfully deleted."
    redirect_to week_path(@physical_task.week)
  end

  private
    def physical_task_params
      params.require(:physical_task).permit(:description, :sunday_value, :monday_value, :tuesday_value, :wednesday_value, :thursday_value, :friday_value, :saturday_value)
    end
  end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :authenticate_user!
  def index
    @weeks = current_user.weeks.all
    # @weeks = Week.all
  end

  def show
    @week = Week.find(params[:id])
    @physical_tasks = @week.physical_tasks()
    # mailchimp = mailchimp.lists.subscribe(MAILCHIMP_LIST_ID),
    #                { "email" => email,
    #                  "euid" => eui,
    #                  "leid" => "23540849e5" }
    @messages = @week.messages()
    if params.include?(:message_id)
                   @message = Message.find(params[:message_id])
  end
end
  #

  def new
    # @week = Week.new
    @week = current_user.weeks.new
  end

  def create
    @week = current_user.weeks.new(week_params)
    # @week = Week.new(week_params)
    if @week.save
      flash[:notice] = "Week successfully added!"
      respond_to do |format|
        format.html { redirect_to weeks_path }
        format.js
      end
    else
      flash[:alert] = "Failure to add week due to error!!"
      render :new
    end
  end

  def edit
    @week = Week.find(params[:id])
  end

  def update
    @week = Week.find(params[:id])
    if @week.update(week_params)
      flash[:notice] = "Week successfully updated!"
      respond_to do |format|
        format.html { redirect_to weeks_path }
        format.js
      end
    else
      flash[:alert] = "Failure to update week due to error!!"
      render :edit
    end
  end

  def destroy
    @week = Week.find(params[:id])
    @week.destroy
    flash[:notice] = "Week successfully deleted!"
    redirect_to weeks_path
  end

private
  def week_params
    params.require(:week).permit(:date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthLists</title>

    <%= yield(:title) %>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">


    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">

        </div>
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
      <% end %>
    </nav>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
    </div>
  </body>
</html>

app/views/messages/new.html.erb
<h1>New message</h1>

<% if @message.errors.any? %>
  <p> Something went wrong:</p>
  <ul>
    <% @message.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>




  <%= form_for [@week, @message] do |f| %>
    <div class="form-group">
      <%= f.label :to %>:
       <%= f.text_field :to %>
       <%= f.label :body %>:
       <%= f.text_field :body %>
     <%= f.submit %>
   <% end %>

app/views/physical_tasks/_form.html.erb
<%= render('layouts/errors', :object => @physical_task) %>

<%= form_for [@week, @physical_task] do |f| %>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description %>
  </div>
  <p><%= f.submit %></p>
<% end %>

app/views/physical_tasks/create.js.erb
$('form').remove();
$('#new_physical_task_link').show();

$('#week_physical_tasks').append('<tr><td><%= @physical_task.description %> | <%= link_to "Edit", edit_week_path(@week, @physical_task), :class => "btn btn-default" %> | <%= link_to "Delete", week_physical_task_path(@week, @physical_task),
                         :data => {:confirm => "Are you sure?",
                         :method => "delete"},
                         :class => "btn btn-danger" %></td>/tr>')

app/views/physical_tasks/edit.html.erb
<h1>Edit task</h1>

<%= render('form') %>

app/views/physical_tasks/edit.js.erb
$('#edit_physical_task_btn').hide().after('<%= j render("form") %>')

app/views/physical_tasks/new.html.erb
<h1>New physical task/goal for <%= @week.date %></h1>

<%= render 'form' %>

app/views/physical_tasks/new.js.erb
$('#new_physical_task_link').hide().after('<%= j render("form") %>')

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/weeks/_form.html.erb
<%= render "layouts/errors", :object => @week %>

<%= form_for @week, remote: true do |f| %>
  <div class="form-group">
    <%=f.label :date %>
    <%= date_field(:week, :date) %>
  </div>
  <%= f.submit :class => "btn btn-primary yeehaw"  %>
<% end %>

app/views/weeks/_week.html.erb
<div class="week">
  <li><%= link_to week.date, week_path(week), id: "week_link" %></li>
</div>

app/views/weeks/create.js.erb
$('form').remove();
$('#new_week_link').show();
$('#weeks').append('<%= j render(@week) %>')

app/views/weeks/edit.html.erb
<h1>Edit week</h1>

<%= render "form" %>

app/views/weeks/index.html.erb
<h1>Weeks</h1>

<ul id='weeks'>

  <% @weeks.each do |week| %>


    <li><%= link_to week.date, week_path(week), id: "week_link" %></li>

  <% end %>
</ul>

<hr>

<%= link_to "Start a New Week", new_week_path%>

<!-- Begin MailChimp Signup Form -->
 <link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
 <style type="text/css">
 	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
 +	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
 +	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
 </style>
 <div id="mc_embed_signup">
 <form action="//test.us14.list-manage.com/subscribe/post?u=7578f4922bad8f7f058c59b1f7f4a31f-us14&amp;id=23540849e5" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
     <div id="mc_embed_signup_scroll">
 	<h2>Subscribe to our mailing list</h2>
 <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
 <div class="mc-field-group">
 	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
 </label>
 	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
 </div>
 <div class="mc-field-group">
 	<label for="mce-FNAME">First Name </label>
 	<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
 </div>
 <div class="mc-field-group">
 	<label for="mce-LNAME">Last Name </label>
 	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
 <div id="mce-responses" class="clear">
 		<div class="response" id="mce-error-response" style="display:none"></div>
 		<div class="response" id="mce-success-response" style="display:none"></div>
 	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
     <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_3a05f993eacab5f8c4d63133f_5170601140" tabindex="-1" value=""></div>
     <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
     </div>
 </form>
 </div>
 <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
 <!--End mc_embed_signup-->

app/views/weeks/new.html.erb
<h1>Start a new week:</h1>

<%= render "form" %>

app/views/weeks/new.js.erb
$('#new_week_link').hide().after('<%= j render("form") %>');

app/views/weeks/show.html.erb
<% content_for(:title, "Health Checklists For Your Week") %>


  <h2 class="sub-header"><%= @week.date %></h2>
  <div class="table-responsive">
    <table class="table table-striped" id='week_physical_tasks'>
      <thead>
        <tr>
          <th>#</th>
          <th>Sunday</th>
          <th>Monday</th>
          <th>Tuesday</th>
          <th>Wednesday</th>
          <th>Thursday</th>
          <th>Friday</th>
          <th>Saturday</th>
        </tr>
      </thead>
      <tbody>

<% @week.physical_tasks.each do |physical_task| %>
<tr>

          <td><%= physical_task.description %> <%= link_to "Edit", edit_week_physical_task_path(@week, physical_task), id: "edit_physical_task_btn",:class => "btn btn-default", remote: true %>
        <%= link_to "Delete", week_physical_task_path(@week, physical_task),
                                 :data => {:confirm => "Are you sure?",
                                 :method => "delete"},
                                 :class => "btn btn-danger" %>
            </td>




<% end %>

        </tr>




    </table>

  </div>

  <p><%= link_to "Add a daily physical task/goal", new_week_physical_task_path(@week), id:"new_physical_task_link", :class => "btn btn-default", remote: true %></p>
  <p><%= link_to "Edit (change the date of this week)", edit_week_path(@week) %></p>
  <p><%= link_to "Delete this entire week", week_path(@week),
                           :data => {:confirm => "You sure?",
                                     :method => "delete",
                                     :class => "btn btn-danger"}
                                      %></p>

  <p><%= link_to "Return to weeks", weeks_path %></p>

  <h3>Send yourself a text with a reminder about your self-care lists</h3>

<ul>
  <% @messages.each do |message| %>
    <li><%= link_to message.id, message_path(message)%></li>
    <% end %>
</ul>

<%= link_to "New message", new_week_message_path(@week) %>

<ul>
  <%%>
</ul>